### ISSUE TITLE
Can't run TeaClient

### ISSUE THREAD

**Issue by peylight** [TeaSpeak/TeaWeb#16]
Hi
I have kubuntu 18.04 and i installed TeaClient.
After execute to run TeaClient I see a Loading popup and then disappeared...
The console log is this:

```
$ TeaClient 

(TeaClient:5875): Gtk-WARNING **: 07:13:08.869: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(TeaClient:5875): Gtk-WARNING **: 07:13:08.869: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(TeaClient:5875): Gtk-WARNING **: 07:13:08.869: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Main app executed!
Spawn loading screen
Spawn window!
request: http://clientapi.teaspeak.de//api.php?type=update-info
Loading ui package
TypeError: Cannot read property 'body' of undefined
    at Request.request.get [as _callback] (/usr/lib/TeaClient/resources/app.asar/updater/updater.js:129:38)
    at self.callback (/usr/lib/TeaClient/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at ClientRequest.<anonymous> (/usr/lib/TeaClient/resources/app.asar/node_modules/request/request.js:819:16)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.emitTimeout (_http_client.js:706:34)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:445:8) 'Uncaught Exception thrown'
TypeError: Cannot read property 'body' of undefined
    at Request.request.get [as _callback] (/usr/lib/TeaClient/resources/app.asar/updater/updater.js:129:38)
    at self.callback (/usr/lib/TeaClient/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at ClientRequest.<anonymous> (/usr/lib/TeaClient/resources/app.asar/node_modules/request/request.js:819:16)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.emitTimeout (_http_client.js:706:34)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:445:8)
```

**Comment by WolverinDEV** [comment]
Use 1.1.0.
Shall be fixed there

**Comment by peylight** [comment]
The bug has been fixed and i see another waiting page and another error in 1.1.1-1:
The dialog error say `Failed to load native extensions: Error: Cannot find module 'teaclient_codec'`
And the CLI log:

```
$ TeaClient 

(TeaClient:10472): Gtk-WARNING **: 00:01:58.732: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(TeaClient:10472): Gtk-WARNING **: 00:01:58.732: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(TeaClient:10472): Gtk-WARNING **: 00:01:58.732: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Main app executed!
Spawn loading screen
Spawn window!
request: http://clientapi.teaspeak.de//api.php?type=update-info
Loading ui package
Local cache: { local_index:
   { channel: 'release',
     version: '1.0.1',
     git_hash: 'f39e0c9',
     timestamp: 1543260464 } }
Got ui info { channel: 'release',
  version: '1.0.1',
  git_hash: 'f39e0c9',
  timestamp: 1543260464,
  required_client: undefined }
Unpacking cached ui info
Unpacked. Target path: /home/peylight/.local/share/TeaClient/tmp/ui/release_1543260464
Successfully downloaded everything!
[console][INFO] Hello World
[console][INFO] /usr/lib/TeaClient/resources/app.asar
[console][INFO] Load for debug!
[console][INFO] Loaded successfully all scripts!
[console][INFO] Runtime init!
[console][INFO] [ '/usr/lib/TeaClient/resources/app.asar/app/native/node_modules',
  '/usr/lib/TeaClient/resources/app.asar/app/node_modules',
  '/usr/lib/TeaClient/resources/app.asar/node_modules',
  '/usr/lib/TeaClient/resources/node_modules' ]
[console][INFO] Loading native extensions...
[console][INFO] require "teaclient_codec"
Stack:
    at Module.a [as require] (/usr/lib/TeaClient/resources/app.asar/app/native/loader_adapter.js:61:29)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/TeaClient/resources/app.asar/app/native/audio/Codec.js:4:22)
    at Object.<anonymous> (/usr/lib/TeaClient/resources/app.asar/app/native/audio/Codec.js:46:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
[console][ERROR] Failed to load audio codec
[console][INFO] { Error: Cannot find module 'teaclient_codec'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/usr/lib/TeaClient/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at Module.a [as require] (/usr/lib/TeaClient/resources/app.asar/app/native/loader_adapter.js:65:32)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/TeaClient/resources/app.asar/app/native/audio/Codec.js:4:22)
    at Object.<anonymous> (/usr/lib/TeaClient/resources/app.asar/app/native/audio/Codec.js:46:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10) code: 'MODULE_NOT_FOUND' }
[console][ERROR] Displaying critical error
[console][INFO] Win: { _events: [Getter/Setter],
  _eventsCount: [Getter/Setter],
  devToolsWebContents: [Getter] }
Gtk-Message: 00:02:02.546: GtkDialog mapped without a transient parent. This is discouraged.

```
